version: "3.7"

services:

  # OCB
  orion:
    image: fiware/orion
    hostname: orion
    container_name: orion
    networks:
      - fiware_network
    depends_on:
      - mongo-db
    ports:
      - "1026:1026"
    environment:
      ORION_LOG_LEVEL: "DEBUG"
      ORION_MONGO_HOST: "mongo-db"
      ORION_MONGO_PORT: "27017"
      ORION_MONGO_DBNAME: "orion"
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1
      interval: 5s
    restart: on-failure

  # Mongo
  mongo-db:
    image: mongo
    hostname: mongo-db
    container_name: mongo-db
    networks:
      - fiware_network
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data

  # Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - fiware_network
    ports:
      - "3000:3000"
    depends_on:
      - orion
      - mongo-db

  # System long-term database
  crate-db:
    image: crate
    hostname: crate-db
    container_name: crate-db
    networks:
      - fiware_network
    expose:
      - "4200"
      - "4300"
      - "5432"
    ports:
      - "4200:4200"
      - "4300:4300"
      - "5432:5432"
    command: crate -Cauth.host_based.enabled=false -Ccluster.name=SSFV -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"

  quantum-leap:
    image: smartsdk/quantumleap
    hostname: quantumleap
    container_name: quantumleap
    networks:
      - fiware_network
    expose:
      - "8668"
    ports:
      - "8668:8668"
    environment:
      - CRATE_HOST=crate-db
    depends_on:
      - crate-db

  # PostgreSQL
  postgres-db:
    image: postgres
    hostname: postgres-db
    container_name: postgres-db
    networks:
      - fiware_network
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "post123"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data

volumes:
  mongo-db: ~
  grafana: ~
  postgres-db-data: ~

networks:
  fiware_network:
    driver: bridge